language: node_js
node_js:
  - node
script: npm test -- --coverage --verbose;
before_deploy:
  - npm pack
  - npm run build
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "*.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    email: "toni.ar.kangas@gmail.com"
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true
