language: node_js
node_js:
  - node
script: npm test -- --coverage --verbose;
before_deploy:
  - npm pack
  - npm run build
deploy:
  - provider: releases
    token: $GITHUB_TOKEN
    file_glob: true
    file: "*.tgz"
    cleanup: false
    edge: true
    on:
      tags: true
  - provider: npm
    email: "toni.ar.kangas@gmail.com"
    api_token: $NPM_TOKEN
    cleanup: false
    edge: true
    on:
      tags: true
